### ISSUE TITLE
Bug: Auto-Publishing as PER failing

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/echidna#1048]
Tried to auto-publish a PER of [Aria in HTML](https://w3c.github.io/html-aria/), but failed:  

Found while trying to publish “echidna.tar” (see the [publication job](https://labs.w3.org/echidna/api/status?id=e14d8a80-7e09-4f39-b9c1-fe3d477f6bc5))

> "Error: Only WD, CR, CRD and Notes are allowed!"

Shouldn't PER be allowed also? 

CC @plehegar.

**Comment by siusin** [comment]
cc @deniak

**Comment by deniak** [comment]
Sorry for the very late reply.
With the recent versions of the [process document](https://www.w3.org/2021/Process-20211102/#revising-rec), we no longer publish PER but instead, RECs with different classes of changes. The type of updates have different requirements (Director's approval, Call for Exclusions, etc) that's why Echidna is not (yet) able to process such documents. That being said, with a bit of work, we should be able to accept revised RECs.

In the meantime, after discussing with Xiaoqian, we can publish html-aria manually. Since the document contains substantive changes, it'll trigger a call for exclusions and after the review, we will be able to republish the REC with the changes.

FYI, the [guide](https://www.w3.org/Guide/transitions?profile=REC&rec=proposed-corrections) lists all the steps needed for each type of edits.

**Comment by marcoscaceres** [comment]
ok, so, to be clear, the current Process wouldn't allow us to auto-publish things on /TR/ if a spec goes to REC? That's totally ok, but just want to make sure we choose the right path for any specs. 

I wonder if we should then take aria-html off this path and just move it to WD as a level 2? The current process is causing some pain for the Editors of that spec, but I had (wrongly) assured them that the pain would be worth it because we could auto-publish (with purple boxes).  

cc @plehegar

**Comment by deniak** [comment]
My understanding of the process is that, to revise a REC, a WG can do the following:
```mermaid
  graph TD;
      REC-->RECC[REC with candidate corrections/additions];
      RECC-->RECP[REC with proposed corrections/additions];
      RECP-->REC
```

FYI, mockups of:
* [REC with candidate corrections/additions](https://w3c.github.io/tr-design/p2021mockup/rec-6.1.5-candidate-addition.html)
* [REC with proposed corrections](https://w3c.github.io/tr-design/p2021mockup/rec-6.2.11.3.html), [proposed additions/corrections](https://w3c.github.io/tr-design/p2021mockup/rec-6.2.11.34.html), [proposed additions](https://github.com/w3c/tr-design/blob/gh-pages/p2021mockup/rec-6.2.11.4.html)

I also understand that publishing a REC with candidate corrections/additions can be done without the director's approval and will not trigger a CfE (https://www.w3.org/2021/Process-20211102/#candidate-amendments) thus can be a good candidate for Echidna and could solve your issue with aria-html.
Then once the group is satisfied with the *candidate* changes, they will need to publish a REC with *proposed* changes which now requires the director's approval and generate a CfE, so it'll be a manual publication.
Once fully reviewed, the WG will then republish the normative REC including the changes (also manual publication).

@plehegar, if this is all correct, it'll require a bit of work so Echidna can support RECs with candidate amendments but I can probably take a day or 2 for this. WDYT?

**Comment by marcoscaceres** [comment]
> I also understand that publishing a REC with candidate corrections/additions can be done without the director's approval and will not trigger a CfE 

This was my original understanding also, and why I pushed the Editors to down this path. But I'd incorrectly assumed we had Echidna support for it. I should have checked. 

> Then once the group is satisfied with the candidate changes, they will need to publish a REC with proposed changes which now requires the director's approval and generate a CfE, so it'll be a manual publication.

Yep... at least, that's also what I read. 

Note that we will now also have Geolocation, Payment Request API, and possibly other specs marked as "updatable-recs", so it's increasingly critical Echidna supports this.... otherwise whole bunch of specs might need to sit as CR until we do.

**Comment by plehegar** [comment]
> I also understand that publishing a REC with candidate corrections/additions can be done without the director's approval and will not trigger a CfE (https://www.w3.org/2021/Process-20211102/#candidate-amendments) thus can be a good candidate for Echidna and could solve your issue with aria-html.

Correct.

>  Then once the group is satisfied with the _candidate_ changes, they will need to publish a REC with _proposed_ changes which now requires the director's approval and generate a CfE, so it'll be a manual publication.

Not quite correct: Publishing a REC with proposed amendments does NOT require Director's approval (see [6.3.11.5](https://www.w3.org/2021/Process-20211102/#change-review)). As such, this is not a transition and won't find it in the set of [choices for transitions](https://github.com/w3c/transitions/issues/new/choose). It does however trigger a CfE and an AC review, thus it's still a manual publication on the Team side. 

> Once fully reviewed, the WG will then republish the normative REC including the changes (also manual publication).

This will require Director's approval, thus it's a transition request ([Recommendation Track - Update a Recommendation](https://github.com/w3c/transitions/issues/new/choose)).

> @plehegar, if this is all correct, it'll require a bit of work so Echidna can support RECs with candidate amendments but I can probably take a day or 2 for this. WDYT?

SGTM.

**Comment by deniak** [comment]
Thanks for the confirmation. I'll start working on this. Hopefully I can deploy the update early next week so it's ready before TPAC.

**Comment by deniak** [comment]
@marcoscaceres, I just deploy the changes so Echidna should now be able to publish REC with *candidate* corrections/additions/amendments.
Pubrules is expecting 2 specific paragraphs to detect the type of REC:
* https://www.w3.org/pubrules/doc/rules/?profile=REC#publish
* https://www.w3.org/pubrules/doc/rules/?profile=REC#recAddition

Let me know if there's any problem.

**Comment by plehegar** [comment]
Now [supported in our transition requirements](https://github.com/w3c/transitions/commit/6778ac051ad2ce2b1e7955e4c3be9e8339b3b8b9)

* https://www.w3.org/Guide/transitions?profile=REC&rec=editorial&echidna=true
* https://www.w3.org/Guide/transitions?profile=REC&rec=candidate-corrections&echidna=true
* https://www.w3.org/Guide/transitions?profile=REC&rec=candidate-additions&echidna=true

**Comment by marcoscaceres** [comment]
Ok, I guess we now need to update the templates on the ReSpec side....

**Comment by siusin** [comment]
> Ok, I guess we now need to update the templates on the ReSpec side....

Yes :)

Btw, the only exit criteria of a REC with Candidate Amendments is a group decision (a CFC), with no requirement on the duration.
