### ISSUE TITLE
Bug: IP X.X.X.X isn't authorized to use the token method

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/echidna#1049]
FYI... failed with: 

✗ Echidna failed to publish “echidna.tar”
for the following reasons:

This IP 140.82.115.100 isn't authorized to use the token method
👎 The token method is restricted to GitHub Actions and Travis CI only. If you want to submit a request outside these tools, please use the tar method.

Found while trying to publish “echidna.tar” (see the [publication job](https://labs.w3.org/echidna/api/status?id=eff2cb79-7f26-4ec5-89a1-f2b00c656538))

**Comment by deniak** [comment]
Echidna relies on https://api.github.com/meta to get the list of GH Actions IPs. However, the IP you are mentioning is listed in the 'hooks' list instead of the 'actions' one. I believe this is not the first time it happens so I added these IPs to the list so hopefully this should fix the issue.

**Comment by marcoscaceres** [comment]
Yep, all good now... seems to be working 🙏
