### ISSUE TITLE
suggest an edit to the Echidna CR publication workflow

### ISSUE THREAD

**Issue by xueyuanjia** [w3c/echidna#1193]
hi @deniak I'm hoping to add the following text to the [CR publication workflow](https://github.com/w3c/echidna/wiki/CR-publication-workflow), after the sentence of "you will need to send the draft transition to w3t-comm@w3.org":

_(and indicate that this will be an Echidna publication)_

So that there's a clear signal to Comm team that we should comment on GitHub, instead of looking/expecting for publication requests on < webreq > where those manual publications are normally sent.

**Comment by deniak** [comment]
Hi @xueyuanjia, I added the following to [the workflow description](https://github.com/w3c/echidna/wiki/CR-publication-workflow#draft-announcement-to-the-members):
`Please, make sure to mention that the document is expected to be published with Echidna and add a link to the transition issue.`
