### ISSUE TITLE
Make sure api/status returns always as JSON (not HTML)

### ISSUE THREAD

**Issue by tripu** [w3c/echidna#126]
The `Content-Type` returned changes, depending on whether that particular job has already finished (thus Echidna dumps the content of a file from disk) or is still being processed (then Echidna returns the object from memory). [`https://github.com/w3c/echidna/blob/master/app.js#L76`](https://github.com/w3c/echidna/blob/master/app.js#L76).

@darobin: *&ldquo;you can replace `res.status(200).send(JSON.stringify(requests[id], null, 2) + '\n');` with `res.json(requests[id])`&rdquo;*.

**Comment by astorije** [comment]
:+1: to @darobin's suggestion.
