### ISSUE TITLE
Description of process for ReSpec users 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/echidna#127]
Can you please add the following to the Wiki? 

====

# How to use Echidna with ReSpec and GitHub

**YOU DON'T NEED TO ACTUALLY INSTALL ENCHIDA AT ALL!**

Before you start - unfortunately, there are a few process things you need to do. **These steps can take about 1-2 weeks to complete**. 

You will need the following:

 1. Working Group Approval to use the new process. 
 1. A token from the W3C. 
 1. The "editor ID"  of each editor of the spec.

## Working Group Approval
In order to publish your document using the new process, you need to get consensus to do so by your Working Group by emailing your group's mailing list. See, for example, how [approval was requested for the WebApps WG](https://lists.w3.org/Archives/Public/public-webapps/2014JulSep/0627.html)

The chair will generally put out a Call for Consensus (CFC), which can take about 1 week. 

Once you get approval (or the CFC), keep the URL handy cause your will need it later to actually publish! 

## The Token
You will need to get a token for your spec from the W3C. You can request this while you are waiting for WG consensus through the CFC (see above)! Email either your team contact or webreq@w3.org.

You will get an email within a few days with your token. 

## The Editor IDs
Then you will need to get the IDs for the Editors of your spec. You can find yours by going to [your W3C profile](https://www.w3.org/users/myprofile):

<image with arrows to where the ID is>

You will need to add this ID to your ReSpec config using the `w3cid` property, like so: 

```JS
editors: [{
    name: "Spec Editor",
    w3cid: 39125
}]
```

## Actually publishing
Welcome back! now that you have all the things above, you can finally proceed to publishing.

1. Go to the root directory where your spec is and make a config file for your spec. Call it ECHIDNA.

```BASH 
touch ECHIDNA
```

1. In ECHIDNA, you need to list the main spec file and any dependent images or other files. For example:

```TEXT 
# ECHIDNA configuration
index.html?specStatus=WD;shortName=appmanifest respec
images/manifest-src-directive.svg
```

1. Save it, and push that back to your gh-pages branch on GitHub. 

```BASH
git checkout gh-pages
git add ECHIDNA
git commit -m "Echidna config" ECHIDNA
git push
```

1 Run your spec over the new PubRules and fix all the errors. PubRules won't accept a raw ReSpec document, so you can basically modify the following to suit your document: 

https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/linkToYourSpec/?specStatus=WD;shortName=theShortName

1. Ok! now run the following using curl. You will need:

 * `url=`: the URL to your echidna config on GitHub, as served from GitHub pages (usually `http://w3c.github.io/YourSpecName/ECHIDNA`). 
 * `decision=`: URL to the working group decision on a w3c mailing list.
 * `token=` the token you got from the W3C. 
 
 Got 'em? Good! now replace all the bits below... 

```BASH
curl 'https://labs.w3.org/echidna/api/request' --data 'url=<echidnaConfigURL>&decision=<decisionUrlOnMailingList>&token=<W3Ctoken> 
```

Finally, once you do that, you can check if your document actually got published by going to the [TR-Notification list](https://lists.w3.org/Archives/Public/public-tr-notifications/). If something went wrong, it will tell you what happened (and hopefully what you need to fix!). 

Otherwise, you should see success! If successful, your Working Draft should now be on /TR/.

**Comment by anssiko** [comment]
Nice guide!

AFAIK, you don't need to install Echinda locally to be able to publish. I learned it the hard way, as I experimented with the thing. That said, I haven't published with it for real, so I may be missing something.

**Comment by marcoscaceres** [comment]
@anssiko ah, you are absolutely totally right! I don't know why I even thought you needed to do that... Updating the above!!!

**Comment by astorije** [comment]
@marcoscaceres, done: https://github.com/w3c/echidna/wiki/How-to-use-Echidna-with-ReSpec-and-GitHub
