### ISSUE TITLE
Echidna appears to corrupt images (probably all binary files)

### ISSUE THREAD

**Issue by darobin** [w3c/echidna#137]
If you compare images as available in the original source (e.g. http://www.w3.org/html/wg/drafts/html/wd/img/sample-details-1.png) with those available in the installed version (the same would be http://www.w3.org/TR/html51/img/sample-details-1.png) you will note some differences.

The most glaring one is that the latter does not work. Running the new file through `file`, it no longer is recognised as PNG. The size has been hugely inflated: 337K instead of 181K.

I haven't looked at the code but the most likely source for this problem is that at some point binary files get treated as text. All the files — including textual ones — should be treated as opaque binaries by this tool chain

**Comment by astorije** [comment]
I am working on that one. I can reproduce the bug (that is, in a test), I will send a PR as soon as I have a fix.

Thanks for pointing that out! In the meantime, I recommend manually replacing the broken image in CVS, considering it's a bug in the tool chain.

**Comment by astorije** [comment]
Et voilà @darobin, fix proposed on #138.
That proves me I really need to work on the manifest thingy...
