### ISSUE TITLE
Improve the Orchestrator#next and the orchestration descriptiveness

### ISSUE THREAD

**Issue by astorije** [w3c/echidna#151]
Per this [comment on #84](https://github.com/w3c/echidna/pull/84/files#r28553039), I could at least centralize the call of `Orchestrator#runStep(/* ... */)(state)`.

~~Another idea would be to have a mechanism to set up the step chaining in a more descriptive way, kind of a [DSL](https://en.wikipedia.org/wiki/Domain-specific_language). That will allow us to have the whole process at one spot almost human-readable. Right now it seems like an overkill as all steps are in sequence, but very soon (actually, now if we could) we'll have parallel executions, maybe ability to rollback, ...~~

~~I am open to suggestions and examples.~~ (Actually, see #158 to start this discussion)

**Comment by tripu** [comment]
I guess this is partially resolved by #153?

I'll leave it to you to decide if that is good enough, or you prefer to close this issue.

**Comment by astorije** [comment]
Fair enough, @tripu, I opened #158 for this.
