### ISSUE TITLE
The actual TR installation script and the cp command are not compatible anymore

### ISSUE THREAD

**Issue by astorije** [w3c/echidna#174]
When reaching the `tr-install` step, we get the following:

```js
{
  status: 'error',
  jobs: {
    // [...]
    'tr-install': {
      status: 'error',
      errors: '[\n  "Error: Command failed: /bin/cp: cannot create directory ‘[...]/TR/2015/WD-navigation-timing-2-20150508/’: No such file or directory\\n"\n]'
    },
    // [...]
  },
  // [...]
}
```

That's because the `/bin/cp -R` command and our internal TR installation script must not have the same behavior: the former one fails when the intermediary folders (therefore `TR` and `2015`) do not exist while the latter one may create them when they don't exist.

However, if the internal script doesn't create `TR` and `2015` folders when they don't exist, Echidna will fail on the first publication of 2016...

I see a couple of solutions here but they don't seem optimal to me. @deniak, what are your thoughts on this on the internal script side?

**Comment by deniak** [comment]
@astorije I think the easiest is to start using the `NODE_ENV` variable to differentiate the production, dev and testing environments.
Having something like:
```
var destination;
if ((process.env.NODE_ENV !== 'production') {
  destination = '/<base>/TR/2015/';
} else {
  destination = '/tmp/';
}
```

Another option would be to have that `destination` in `config.js`. It's a bit like what you are trying to do with the `replace` in your [commit](https://github.com/w3c/echidna/commit/9ba55035e41a504c2465eecab5a1028d80b09c9e#diff-7d4f494095ebbff79fc20b6b2df52766R21) but imo, easier to follow if the destination is in the config file.
