### ISSUE TITLE
Wrong URL in e-mail notifications after successful publication

### ISSUE THREAD

**Issue by tripu** [w3c/echidna#188]
The &ldquo;OK&rdquo; e-mail used to include the URL of the newly published spec ([example](https://lists.w3.org/Archives/Public/public-tr-notifications/2015Jun/0000.html)). After deploying [`v1.2.2`](https://github.com/w3c/echidna/releases/tag/v1.2.2) that template now includes the URL of the *source* used to publish instead ([example](https://lists.w3.org/Archives/Public/public-tr-notifications/2015Jun/0004.html)).

(Maybe a bug introduced during #84? I'll investigate.)

**Comment by astorije** [comment]
Oops, most likely, sorry! :-)
