### ISSUE TITLE
Token generator should accept HTTPS

### ISSUE THREAD

**Issue by darobin** [w3c/echidna#190]
This is just a paper cut. I am reporting it here even though the code lives elsewhere. The problem is best illustrated here:

![echidna](https://cloud.githubusercontent.com/assets/38491/7955690/8a7c44c6-09da-11e5-92f1-4e054ff4aa15.png)

Either the token creation form should accept `https`, or it should just take the short name.

**Comment by astorije** [comment]
I'd agree, but `/TR/` is not (and is not planning to be) under HTTPS, right?

**Comment by tripu** [comment]
Yes, entering only the shortname in that field would be simpler, and safer: it'll still work when/if the first portion of the URL changes&hellip;

**Comment by darobin** [comment]
@astorije I know it's the case now, but I would hope at least some of it can switch some day. In either case, applications should think for you when they disagree ;)

**Comment by tripu** [comment]
[Moved to team-only Trac, where we handle issues about this piece of the system; ticket # 103.]

Thanks, @darobin :)
