### ISSUE TITLE
E-mail notifications of success don't include the URL of the published spec

### ISSUE THREAD

**Issue by tripu** [w3c/echidna#195]
&ldquo;OK&rdquo; notifications used to include [the URL of the newly published spec](https://lists.w3.org/Archives/Public/public-tr-notifications/2015Jun/0000.html).

After deploying [`v1.2.2`](https://github.com/w3c/echidna/releases/tag/v1.2.2), they include [the URL of the *source* (HTML or manifest) instead](https://lists.w3.org/Archives/Public/public-tr-notifications/2015Jun/0008.html).

**Comment by astorije** [comment]
Well, you already fixed this one in [e8abe26, line 133](https://github.com/w3c/echidna/commit/e8abe26961f12147a510624a768911d2acc88f12#diff-0364f57fbff2fabbe941ed20c328ef1aR133) :-)

**Comment by tripu** [comment]
@astorije: did I? OhgoshI'msogood.

Now seriously: I wasn't 100% sure that my commit fixed this issue, without introducing other errors when the result is "failure". I left this open because I wanted to come back to those changes, and review. But I think you're right. I'll confirm when that's deployed.

Thanks!
