### ISSUE TITLE
So that nsp thing...

### ISSUE THREAD

**Issue by astorije** [w3c/echidna#212]
![image](https://cloud.githubusercontent.com/assets/113730/8767045/acd98f04-2e4e-11e5-9ea8-0616cee769af.png)

When running `time npm test` with the `nsp` check disabled, considering tests are passing, we get:

```
> echidna@1.2.2 test /Users/jeremie/Perso/echidna
> npm run check-style && npm run lint && mocha

[...]

real    0m5.288s
user    0m3.688s
sys     0m0.416s
```

Now, with the `nsp` check, we get:

```
> echidna@1.2.2 test /Users/jeremie/Perso/echidna
> npm run nsp && npm run check-style && npm run lint && mocha

[...]

real    0m18.960s
user    0m3.408s
sys     0m0.484s
```

Add to that the tests (they were not run because `nsp` currently fails), you get a total time of 24+ seconds compared to the previous ~5 seconds.

Not that 24 seconds is a long time, but I don't think it's worth the wait here. I suggest to remove it from `npm test` but to keep the script so that `npm run nsp` can still be run.

**Comment by tripu** [comment]
I don't mind CI builds taking as long as necessary&hellip; but OK to remove nsp from CI, @astorije.

I only fear nobody will run it ever if it's not automated, so we'll miss security updates.

nsp will be the new David: fancy, but not really useful if it doesn't slap someone on the face hard enough :)

**Comment by tripu** [comment]
(Assigned to @deniak to give him the last word. Sorry, mate&hellip;)

**Comment by astorije** [comment]
> I don't mind CI builds taking as long as necessary… but OK to remove nsp from CI, @astorije.

@tripu, I am not suggesting to remove it from CI (although you might end up wanting too if you really want to detect good and bad PRs), but just from the `npm test` script. Then you can have Travis CI run it before or after the tests (after the tests would be better so at least you know if tests pass).
