### ISSUE TITLE
Echidna sometimes discloses internal infrastructure details in log messages

### ISSUE THREAD

**Issue by tripu** [w3c/echidna#221]
When there are errors reported in the JSON output, we have sometimes seen [hostnames, ports and the like being mentioned](https://lists.w3.org/Archives/Public/public-tr-notifications/2015Aug/0030.html) (of machines that are behind the labs.w3.org proxy). That doesn't give useful information to users (it's rather confusing to them), and it isn't wise to disclose that info, security-wise.

Leave those pieces of information out of the user messages.

**Comment by deniak** [comment]
Duplicate #134
