### ISSUE TITLE
Token request form is confusing

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/echidna#225]
I only request publication token rarely, so I'm newly confused each time I use the [request token form](https://www.w3.org/Web/publications/register).

Suggestions to help me (and hopefully others):
* indicate that the form can be used both to obtain a new and update an existing token
* explain how the source URL will be used (as a filter for URLs from which the document will be fetched)
* for the source example, give "https://w3c.github.io/" rather than https://www.github.com/w3c/

**Comment by deniak** [comment]
The form has been updated and hopefully, is less confusing.
Thanks for the feedback.
