### ISSUE TITLE
[feature request] Upload tar or zip file

### ISSUE THREAD

**Issue by deniak** [w3c/echidna#230]
From [Bert's whishlist](https://lists.w3.org/Archives/Public/public-pubrules-comments/2015Sep/0000.html)

> Ability to upload a tar or zip file, instead of having to put the 
> files on a  server somewhere. (My machine is behind a NAT, I can't serve 
> the files from my own machine.)

**Comment by astorije** [comment]
I remember bringing that idea back when I was W3T and it was strongly disapproved, for security issues. The rationale was that if you allow TAR or ZIP extraction then you open yourself to a world of pain.

After that explanation, I could only agree, but I don't remember the details. @tguild and @gosko, do you mind giving your thoughts here for definitive explanation/examples?

**Comment by deniak** [comment]
Yes, there are security consideration about uploading such files on our servers that's why we went for the manifest. For those who have team access, see https://lists.w3.org/Archives/Team/w3t-sys/2014JanFeb/thread.html#msg159

**Comment by tripu** [comment]
This feature request is fresh again after a discussion with people using Bikeshed during TPAC2015.

**Comment by tripu** [comment]
Agreed after TPAC that ZIP is too risky a format; looking at uncompressed tarballs or so now.

**Comment by tripu** [comment]
(Note: I started playing with [`tar`](https://www.npmjs.com/package/tar); @deniak investigated [`tar-stream`](https://www.npmjs.com/package/tar-stream) instead. I'm letting him continue for now; happy to help if needed!)
