### ISSUE TITLE
Deliberate change of editors

### ISSUE THREAD

**Issue by plehegar** [w3c/echidna#240]
Right now, Echidna rejects documents if editors are changed, but that could be intentional.

**Comment by tripu** [comment]
Do you have an example, @plehegar?

**Comment by deniak** [comment]
@plehegar if you are referring to http://teole.jfouffa.org/cssfun/index.html, the [message](https://lists.w3.org/Archives/Public/public-tr-notifications/2015Dec/0004.html) says:
```
Documents returning to WD are not supported yet.
```
That's because the current version on /TR is a LC.

**Comment by plehegar** [comment]
I don't have a specific example but editors do change from time to time. Why should one go through manual publishing just because an editor has been added?

**Comment by plehegar** [comment]
(and btw, yes, I don't think we need to support LC->WD)

**Comment by tripu** [comment]
I'd wait until that happens for the first time, then&nbsp;&mdash;&nbsp;to confirm that Echidna rejects that document, and then fix it.

**Comment by deniak** [comment]
@plehegar I checked the backend and echidna will not block editor changes so this ticket can be closed.
