### ISSUE TITLE
github.io mirroring delay

### ISSUE THREAD

**Issue by deniak** [w3c/echidna#250]
@tguild noticed a delay in github.io mirroring. Sometimes, it takes a few seconds/minutes for the commit to be propagated on github pages but if the webhook is configured for that repo, Echidna will not take the latest updates as it's not available yet on github.io.

@tguild suggested we could post an expected minimum timestamp with the request so Echidna could compare it with the one from github.io.

Another option might be to use raw.githubusercontent.com instead of github.io (eg. https://raw.githubusercontent.com/w3c/automotive/gh-pages/vehicle_data/Echidna.data).

**Comment by tripu** [comment]
I think this won't be a problem when we're done with #245. Any group using github.io now could pass along their `gh-pages` branch directly to Echidna; no web publishing necessary so that delay won't matter.
