### ISSUE TITLE
Bogus "change of deliverers" error

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/echidna#251]
https://lists.w3.org/Archives/Public/public-tr-notifications/2016Jan/0026.html failed, claiming the publication attempted to change the deliverers of the spec, but it didn't.

/cc @anssiko

**Comment by anssiko** [comment]
I've seen this error in other legitimate cases (then with Web App Manifest migrating from WebApps to WP WG), and for that what did the trick per @plehegar advise was to do "a manual publication first to unlock echidna".

Is it possibly the TF that is the union of two WGs that triggers the same error with Echinda?

Specifically, in the ReSpec source for this spec `respecConfig.wg` is an array with two entries: https://github.com/w3c/mediacapture-depth/blob/TR/index.html#L42

**Comment by deniak** [comment]
That's definitely a bug. Might be related to an upgrade of the backend.
I'll debug it

**Comment by deniak** [comment]
The bug is now fixed.

**Comment by anssiko** [comment]
Thanks!
