### ISSUE TITLE
Unknown source for tar upload

### ISSUE THREAD

**Issue by deniak** [w3c/echidna#252]
The token checker is expecting a source url which doesn't exist when someone uploads a tarball to Echidna

**Comment by tripu** [comment]
One possibility: to add support for [Bikeshed](https://github.com/tabatkins/bikeshed) to [spec-generator](https://github.com/w3c/spec-generator), so that we can generate the CSS WG's specs on the fly from their published `.bs` sources. That might remove the need for TAR-upload altogether.

**Comment by deniak** [comment]
From a past meeting, we decided to rely on the W3C authentication mechanism for tar uploads
