### ISSUE TITLE
MathJax integration issues

### ISSUE THREAD

**Issue by anssiko** [w3c/echidna#271]
[Branching this issue from w3c/respec#678]

@dontcallmedom thanks for fixing the spec-generator bug. Current status with mediacapture-depth WD publication attempt:

* [Fails Echidna with a MathJax-related validator.css error](https://lists.w3.org/Archives/Public/public-tr-notifications/2016Apr/0025.html)
* [spec-generator output][1]
* [PubRules checker output (see errors in validation.css)](https://labs.w3.org/pubrules/?url=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%253A%252F%252Frawgit.com%252Fw3c%252Fmediacapture-depth%252FTR%252Findex.html%253FspecStatus%253DWD%253BshortName%253Dmediacapture-depth&profile=WD&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004&processDocument=2015)

It seems while the MathJax CommonHTML output fixed the HTML validation errors, MathJax-related CSS validation errors surface.

Below is my attempt to debug this:

I extracted the styles from the [spec-generator output][1] with:
```
var styles = '';
[].forEach.call(document.querySelectorAll('style'), function(css) {
  styles += css.innerHTML;
});
console.log(styles);
```
... and tried to look at whether [css-validator](https://jigsaw.w3.org/css-validator/) would give more informative debug log. Errors reported:

```
Sorry! We found the following errors (13)
URI : TextArea
6	#MathJax_About	attempt to find a semi-colon before the property name. add it
6	#MathJax_About	Property progid doesn't exist : DXImageTransform
6	#MathJax_About	Parse Error DXImageTransform.Microsoft.dropshadow(OffX=2, OffY=2, Color='gray', Positive='true')}
8	.MathJax_Menu	attempt to find a semi-colon before the property name. add it
8	.MathJax_Menu	Property progid doesn't exist : DXImageTransform
8	.MathJax_Menu	Parse Error DXImageTransform.Microsoft.dropshadow(OffX=2, OffY=2, Color='gray', Positive='true')}
32	.MJX_Assistive_MathML	Property user-select doesn't exist : none
34	#MathJax_Zoom	attempt to find a semi-colon before the property name. add it
34	#MathJax_Zoom	Property progid doesn't exist : DXImageTransform
34	#MathJax_Zoom	Parse Error DXImageTransform.Microsoft.dropshadow(OffX=2, OffY=2, Color='gray', Positive='true')}
582	.mjx-menclose > svg	Property fill doesn't exist : none
582	.mjx-menclose > svg	Property stroke doesn't exist : currentColor
589	.mjx-span	Value Error : display span is not a display value : span
```
Findings:
* `attempt to find a semi-colon before the property name`
 * Seem like false positives to me, css-validator bug?
* `Property progid doesn't exist : DXImageTransform`
 * A non-standard property, so this error seem legit.
* `Parse Error DXImageTransform.Microsoft.dropshadow(OffX=2, OffY=2, Color='gray', Positive='true')}`
 * Ditto.
* `Property fill doesn't exist : none` and `svg Property stroke doesn't exist : currentColor`
 * These properties deal with SVG shapes, perhaps css-validator fails due to that -- these are [defined in SVG 1.1](https://www.w3.org/TR/SVG/painting.html).
* `display span is not a display value : span`
 * It seems `span` is not a valid value for `display` property. Legit error.

Ping @pkra re the MathJax CSS validation errors: css-validator reports the above errors using the generated output and the CommonHTML profile.

[1]: https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawgit.com%2Fw3c%2Fmediacapture-depth%2FTR%2Findex.html%3FspecStatus%3DWD%3BshortName%3Dmediacapture-depth

**Comment by anssiko** [comment]
Related MathJax/mathjax#1440

**Comment by pkra** [comment]
Thanks, I've filed https://github.com/mathjax/MathJax/issues/1443

**Comment by pkra** [comment]
Just to add: 

* the SVG ones should be ok, imho.
* we still support IE8 (and even 6 with the HTML-CSS output) so DXImageTransform is not a bug from our point of view. But since you pre-process, you can just drop the entire `MathJax_Menu` stuff since you won't have the MathJax menu around. (Similarly the About and Zoom). Again, mathjax-node is a bit more streamlined.

Out of curiosity, what input are you using?

**Comment by anssiko** [comment]
See the [input](https://raw.githubusercontent.com/w3c/mediacapture-depth/TR/index.html) that is passed to spec-generator to produce static [output](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawgit.com%2Fw3c%2Fmediacapture-depth%2FTR%2Findex.html%3FspecStatus%3DWD%3BshortName%3Dmediacapture-depth). The output should pass the W3C PubRules as you probably know.

This is a step in the Echidna workflow W3C uses to automate spec publishing.

**Comment by pkra** [comment]
> See the input that is passed to spec-generator to produce static output. 

Thanks. This is a bit confusing to me. The inline configuration asks for MathML input but MathJax is then told to load the asciimath input (AM_CHTML). Is this intentional?

**Comment by anssiko** [comment]
Good catch! That's a bug. I'll get back to this next week. Have a nice weekend :)

**Comment by pkra** [comment]
> That's a bug. 

FWIW, it's not a problem for MathJax; it will just load both input components. You might want all three input options anyway;_ I don't know.

**Comment by anssiko** [comment]
@pkra Thanks for the suggestions. I fixes this by adding a (rather hack-ish) build step that makes use of mathjax-node, see https://github.com/w3c/mediacapture-depth/commit/58a301489238187f4e5652546fdbfa449e94e29c

Now that the MathJax enabled spec pass Pubrules, we were able to published an updated WD at https://www.w3.org/TR/mediacapture-depth/

I'd consider this build step a workaround, rather than a long-term reusable solution.

@pkra Do you think MathJax could provide a standards-compat config flag to produce output that would passes css-validator out of the box?

I will close this issue now, since this addressed the immediate issue.

**Comment by pkra** [comment]
> Do you think MathJax could provide a standards-compat config flag to produce output that would passes css-validator out of the box?

Is this is only about the DXImageTransform? That could be done but the larger problem is that MathJax on the client is very different from mathjax-node (for historic reasons; mathjax-node is a very recent addition). 

Since phantomJS means client-side rendering, the DOM gets "polluted" with lots of things, both UI (menu handlers and styles -- causing the issues here) as well as markup (e.g., custom-type script tags, empty preview tags, visually hidden MathML for some screenreaders). We're planning to revise much of this in MathJax v3 but that's in its design phase right now. So if you wanted clean markup, mathjax-node is  a little easier -- or you could add some clean-up code to run after MathJax is done.

**Comment by anssiko** [comment]
@pkra There is more than the `DXImageTransform`. To make validators happy, the node script does the following to the ReSpec source `index.src.html`:

 - move all `<style>` blocks to `<head>`
 - remove styles that fail css-validator
 - remove the MathJax.js `<script>` (after it has been executed)
 - remove `@font-face` CSS at-rules (not strictly required to pass, but default font was fine)

The resulting `index.html` passes Pubrules and is provided to Echidna.

For all the dirty details see https://github.com/w3c/mediacapture-depth/blob/gh-pages/build.js

I wouldn't recommend this as the generalized solution, it is a workaround. If mathjax-node would output valid CSS then integration would be easier, so perhaps v3 will mean easier integration with Echidna.

**Comment by pkra** [comment]
> move all <style> blocks to <head>

Good point.

> remove styles that fail css-validator

Note that the SVG styling that you're removing is valid AFAIK. It might also compromise the output.

> remove the MathJax.js <script> (after it has been executed)

I'm not sure why this is necessary. Does your source html have a MathJax script tag? It doesn't need to if you're processing with mathjax-node.

> remove @font-face CSS at-rules (not strictly required to pass, but default font was fine)

This will very easily break the output. Don't do it or switch to the SVG output (which uses paths).

> For all the dirty details see https://github.com/w3c/mediacapture-depth/blob/gh-pages/build.js

I see from the link that this is about mj-page, not client-side MathJax in phantomJS (which I was referring to earlier).

>  If mathjax-node would output valid CSS then integration would be easier,

Just to double check: I only see the `display:span` bug if you're talking about mathjax-node. Yes, that should be fixed.
