### ISSUE TITLE
Moment is deprecating some date formats

### ISSUE THREAD

**Issue by deniak** [w3c/echidna#277]
https://github.com/w3c/echidna/blob/master/lib/publisher.js#L41

Echidna currently gets the `docDate` from Specberus which [sends the date](https://github.com/w3c/specberus/blob/master/lib/validator.js#L214) in a format that is now deprecated in Moment.

**Comment by deniak** [comment]
After https://github.com/w3c/specberus/commit/9b0907b212b8660b38d7ed12cd4ee51ddcf790a5 is merged, https://github.com/w3c/echidna/blob/master/lib/publisher.js#L41 should be updated to
`date: new Moment(metadata.get('docDate'), 'YYYY-MM-DD').format('YYYY-MM-DD'),`

**Comment by tripu** [comment]
cf moment/moment#1407
