### ISSUE TITLE
Should echidna sends an email to the WG public mailing list after a success?

### ISSUE THREAD

**Issue by deniak** [w3c/echidna#285]

**Comment by tripu** [comment]
That is a good idea, @deniak.

Only drawback I can think of is too much noise sometimes (when groups publish upon every single commit or whatever).

It would be ideal if groups can turn that on and off at will. Or maybe we can add an optional boolean parameter to Echidna meaning &ldquo;send notif to public ml&rdquo;.

**Comment by dontcallmedom** [comment]
As alluded in #308 I think it should be best left to the one submitting the job to specific what email address needs to be notified of what.

(note that github-notify-ml already enables groups to get notified of successful TR publications based on the publication webhook)

**Comment by deniak** [comment]
OK, so the new proposal would be to add an optional parameter `email` when someone sends a request to Echidna and add that email address to the list of recipients.
If people are interested in that proposal, :+1: that issue

**Comment by plehegar** [comment]
:+1: modulo the fact that it could be misused, ie I'm tempted to always put email=webreq :)

**Comment by deniak** [comment]
It is now possible to provide a list of email addresses to get the echidna notification (see [wiki](https://github.com/w3c/echidna/wiki/How-to-use-Echidna#using-echidna-publication-without-curl))
