### ISSUE TITLE
form to submit a request to Echidna

### ISSUE THREAD

**Issue by deniak** [w3c/echidna#297]
People who aren't familiar with CLI could benefit from a simple form to submit their documents to Echidna. How does it sound?

**Comment by tripu** [comment]
It sounds like a good idea.

Maybe we should throttle requests coming from that web form, or have a simple CAPTCHA there. A web page makes it easier for crawlers and script kiddies to cause annoyance (compared to the CLI REST interface).

**Comment by tripu** [comment]
[What I did in branch `web-interface`](https://github.com/w3c/echidna/compare/tripu/web-interface) is still working (visit `/ui` to see the UI): filling in a form to send a new publication job, and polling the API to retrieve its status and display it on the same page. Perhaps we'll have to add support to attach a TAR file (cf w3c/specberus#357)?

I'd like the look & feel to be in sync with Specberus, though. I suggest we reuse from that branch only the HTML forms and the JS logic, and start over in a new branch. To have consistent headers and footers, I'd also start using Handlebars templates too, like those we have in Specberus.

@deniak, let's chat before any of us resumes this work, to avoid redundant work.

**Comment by deniak** [comment]
@tripu Let's keep that for later. It's very low priority and it's only an idea. So far no one expressed the need for such form.

**Comment by tripu** [comment]
Yes, low priority, @deniak.

I thought at least one user asked for an HTML form to request publications.
