### ISSUE TITLE
status says "started" but it seems to have succeeded actually...

### ISSUE THREAD

**Issue by plehegar** [w3c/echidna#301]
after 20 seconds following the job creation, I got the following result:
[[
{"id":"aef7128d-e8c3-4565-8923-b3c24526c56a","url":"https://w3c.github.io/resource-hints/W3CTRMANIFEST","version":"1.9.1","version-specberus":"1.5.3","decision":"http://www.w3.org/2015/02/11-webperf-minutes.html#item07","results":{"status":"started","jobs":{"retrieve-resources":{"status":"ok","errors":[]},"metadata":{"status":"ok","errors":[]},"specberus":{"status":"ok","errors":[]},"token-checker":{"status":"ok","errors":[]},"third-party-checker":{"status":"ok","errors":[]},"publish":{"status":"ok","errors":[]},"tr-install":{"status":"ok","errors":[]},"update-tr-shortlink":{"status":"pending","errors":[]}},"history":[{"time":"2016-05-27T13:35:02.753Z","fact":"The file has been retrieved."},{"time":"2016-05-27T13:35:02.850Z","fact":"The metadata have been extracted."},{"time":"2016-05-27T13:35:04.977Z","fact":"The document passed Specberus."},{"time":"2016-05-27T13:35:10.381Z","fact":"The document passed the third party checker."}],"metadata":{"previousVersion":"http://www.w3.org/TR/2016/WD-resource-hints-20160517/","delivererIDs":[45211],"docDate":"2016-05-27T00:00:00.000Z","shortname":"resource-hints","profile":"WD","editorIDs":[56102],"process":"http://www.w3.org/2015/Process-20150901/","latestVersion":"http://www.w3.org/TR/resource-hints/","title":"Resource Hints","thisVersion":"http://www.w3.org/TR/2016/WD-resource-hints-20160527/","editorsDraft":"https://w3c.github.io/resource-hints/","rectrack":true}}}
]]

the overall status says "started", but the job was successful since it returned the dated URI, wasn't it successful?

**Comment by deniak** [comment]
The last job (`update-tr-shortlink`) is still pending.
https://labs.w3.org/echidna/api/status?id=aef7128d-e8c3-4565-8923-b3c24526c56a now shows the status "success"

**Comment by plehegar** [comment]
missed it. thanks!
