### ISSUE TITLE
Status of a job is not available while the request is being processed if echidna is running in cluster mode

### ISSUE THREAD

**Issue by deniak** [w3c/echidna#302]
If we have 2+ instances of Echidna, the status of a job might not be available while the request is being processed. That's because during that time, `/api/status` looks for an allocated var instead of the final json. So the result will depend on the instance handling the request.

**Comment by tripu** [comment]
@deniak, do your recent changes in the way we use pm2 affect this?

**Comment by deniak** [comment]
> @deniak, do your recent changes in the way we use pm2 affect this?

No, we still run 2 instances of Echidna and we will hit the issue while the request is being processed. If we want to fix the problem, we need to revise the way the results are stored before they are getting dumped.
