### ISSUE TITLE
Send better e-mail, and simplify how we do it

### ISSUE THREAD

**Issue by tripu** [w3c/echidna#308]
- [ ] **More descriptive and succinct**: explain upfront what was published; or else which step failed, and how exactly it failed. Don't dump the JSON result.
- [ ] **Attach the complete JSON report** for details and debugging.
- [ ] **Format mail** for better readability (either HTML+CSS, or at least compose it better in plain text).
- [ ] **Get rid of [the fragile Bash script](https://github.com/w3c/echidna/blob/master/sendmail.sh)** and instead send mail directly from Node.js. Some packages to explore:
  - [`nodemailer`](https://www.npmjs.com/package/nodemailer).
  - [`pixl-mail`](https://www.npmjs.com/package/pixl-mail).
  - [`x-mail`](https://www.npmjs.com/package/x-mail).
  - [`staticcss`](https://www.npmjs.com/package/staticcss).
- [x] **Include the URL of the &ldquo;decision to publish&rdquo;** as suggested by @aaronpk (w3c/specberus#529).

**Comment by dontcallmedom** [comment]
Also, it would be nice if one could pass to echidna as a parameter the email address to which the notification should be sent (possibly a different one for failure and for success)

**Comment by tripu** [comment]
[Smashing Magazine: &ldquo;An Introduction To Building And Sending HTML Email For Web Developers&rdquo;](https://www.smashingmagazine.com/2017/01/introduction-building-sending-html-email-for-web-developers/)
