### ISSUE TITLE
Misleading error: Echidna reports "can't change shortname" when the problem is just https on the link

### ISSUE THREAD

**Issue by tabatkins** [w3c/echidna#316]
In the job <https://labs.w3.org/echidna/api/status?id=9622c9c3-ffc2-463b-872b-816e29b69562>, it reports an error during the "publish" step claiming that `"Error: Documents changing their shortname are not supported yet."`.  But the document (css-align-3) has the same shortname as the current /TR version (<https://www.w3.org/TR/css-align-3/>).

Turns out the actual problem is the https on the "This Version" link.  Switching it to http got it through the check.  Echidna should either accept https (I know, that's ongoing) or report a correct error message so the problem can actually be fixed.

**Comment by tabatkins** [comment]
Found the source of the problem and updated the title/text accordingly. (Still a bug to fix.)

**Comment by plehegar** [comment]
one additional thought on this: if we are able to switch to https only, it will be *very* valuable to have a meaningful error message if the editor uses http, otherwise we'll get frustrated folks not realizing our switch over to https.

**Comment by deniak** [comment]
That was a bug with the order of the final checks in the backend. It should now be fixed and if it happens again, you should get the following message:
> Cannot find the latest version specified. It should NOT be a https link.

Note, this will change as soon as we will enforce https.
