### ISSUE TITLE
user search

### ISSUE THREAD

**Issue by plehegar** [w3c/echidna#317]
https://github.com/w3c/echidna/wiki/Preparing-your-document#data-editor-id
says to use
 https://www.w3.org/users/search
to find editor ids but that page is under ACLs and no many people can access it.

On the end, many seems to be able to access:
 https://www.w3.org/2000/09/dbwg/person

**Comment by deniak** [comment]
https://www.w3.org/users/search is restricted to the W3C team only.
I'll add the second link to the wiki so members can find the id too.
