### ISSUE TITLE
Support FPWD

### ISSUE THREAD

**Issue by tripu** [w3c/echidna#376]
High-level meta-issue to keep track of tasks involved:

* [ ] Automate approval of FPWD requests by the director:  
Echidna API / Echidna web UI / **GH issues** ⬅️ / some other approach.
* [ ] What to do with [spec groups](https://www.w3.org/TR/):  
leave as open categories / **fix a discrete list, with public input** ⬅️ / discontinue altogether.
* [ ] How to fill in the description of the new spec:  
provided by the editor / provided by the director / extracted automatically from abstract.
* [ ] How to send the CfE:  
**Do from new IPP Symfony code or script** ⬅️ / do from Echidna / &hellip;
* [ ] &hellip;

**Comment by tripu** [comment]
@deniak, @plehegar :arrow_up:

**Comment by plehegar** [comment]
We need also a description of the specification for /TR, or we could extract the abstract automatically and use it.

**Comment by tripu** [comment]
Thansk, @plehegar; added to the list.

**Comment by caribouW3** [comment]
When we are able to support this use case, then we can also support the case that #409 is forbidding.

**Comment by plehegar** [comment]
Regarding the "How to send the CfE", the current consensus is to do it from the new IPP Symfony code. Echidna will basically not deal with CfE but must provide the information with the FPWD is intended to become a Recommendation or not.

**Comment by plehegar** [comment]
Regarding "Automate approval of FPWD requests by the director", the current consensus is to have a GitHub issues approach, ie we move FPWD requests to GitHub, the Director will approve the transition there, and echidna will pick that up directly.

**Comment by tripu** [comment]
(Description updated to highlight these tentative approaches.)

**Comment by tripu** [comment]
Ways to ensure quality and consistency of FPWDs after they've received a green light?

Restrict publication of FPWDs to team contacts (W3C staff) by TAR attaching (so that we can check they're staff)?

**Comment by tripu** [comment]
Will the IPP script take care of sending the announcement to chairs, automatically?

**Comment by caribouW3** [comment]
IPP only sends CfE (currently to comm, so they can edit if necessary). We have discussed automated CfEs in the past but since there are cases that require editing, an entirely new system seems necessary.

**Comment by deniak** [comment]
This is out of scope for the moment

**Comment by caribouW3** [comment]
For the record: since IPP2019 all CfEs are automated.
