### ISSUE TITLE
Make it clear on the web interface what fields are compulsory

### ISSUE THREAD

**Issue by tripu** [w3c/echidna#38]
Right now, if you enter the URL of the document and the token, but leave blank the _WG decision URL_ field, Echidna ignores you miserably when you click the _request publication_ button.

Make it clear on the form that all 3 fields are mandatory, and disable the button unless all three have data.

**Comment by astorije** [comment]
I'll think of the UI when you guys are busy on the backend integration, I'll keep that in mind :)

**Comment by tripu** [comment]
Fixed in de3e7f46563dd5018e395a38d755a7bd38cb1951 (in branch `web-interface`).
