### ISSUE TITLE
Wrong PP Status for Notes

### ISSUE THREAD

**Issue by deniak** [w3c/echidna#392]
Notes should have the status: not on REC-track

**Comment by tripu** [comment]
cf https://www.w3.org/pubrules/doc/rules/?profile=WG-NOTE#patPolReq

**Comment by tripu** [comment]
@plehegar, shall we change that boilerplate for notes, to make it explicit that notes are *not* on REC-track?

**Comment by plehegar** [comment]
I don't see a diff between the PP boilerplate for a WD on the REC-track and the PP boilerplate for a WG Note. We should definitively have some according to @wseltzer .

Currently, we put:
[[
This document was produced by a group operating under the 5 February 2004 W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy. 
]]

It doesn't say if the present document is covered by the patent policy or not. One has to know if it's intended to become a Rec or not.

For Rec-track, we could say: "This document was produced by a group operating under the 5 February 2004 W3C Patent Policy and is covered by the W3C Royalty-Free (RF) Licensing requirements."

For non-Rec-track, we could say: "This document was produced by a group operating under the 5 February 2004 W3C Patent Policy but the W3C Royalty-Free (RF) Licensing requirements are not applicable."

**Comment by tripu** [comment]
Solved, see eg https://labs.w3.org/echidna/api/status?id=2c0ac938-c37a-4797-9483-ee902ea9d001
