### ISSUE TITLE
Auto-pub for repos with 2+ versions

### ISSUE THREAD

**Issue by siusin** [w3c/echidna#397]
For specs that maintain 2+ versions in a single repo, is it possible to enable auto-pub by new events in the branches?

**Comment by tripu** [comment]
Yes, it is feasible.

If you plan to use Travis CI, it can be configured to build in different ways, depending on the branch where a commit was done. See [`docs.travis-ci.com/user/customizing-the-build/`](https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches).

Note that on GitHub, that approach has other disadvantages. For example, only one of the branches can be the source of GitHub Pages, so not all specs would be accessible via `w3c.github.io/<WG>/`. Also, the resulting workflow may be cumbersome: contributors are used to spawning new branches for corrections and additions to the spec, but in that case I guess there would be *sets of branches* instead (one set of branches per spec).

We do not recommend this setup, in general. It is generally easier to have one spec per repo. If the WG is concerned about redundancy (ie, if they want to reuse resources or snippets across multiple specs), explore other solutions instead, such as [Git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules).
