### ISSUE TITLE
JSON results are unformatted (no linebreaks/indents) on success

### ISSUE THREAD

**Issue by tabatkins** [w3c/echidna#438]
When there's an error in publication, the JSON at the job-results endpoint is nicely formatted and relatively easy to read.  But when the publication is successful, the outputted JSON is compact, with no linebreaks or indentation, and thus very difficult for humans to read.

**Comment by tripu** [comment]
@tabatkins, can you point to an example?

I've tried a few successful ones, and they look okay. This is [the last one](https://lists.w3.org/Archives/Public/public-tr-notifications/2017May/index.html#msg71):

```
$ curl https://labs.w3.org/echidna/api/status?id=1d1d6bb8-5985-46c4-bc70-b2c2e627df04
{
  "id": "1d1d6bb8-5985-46c4-bc70-b2c2e627df04",
  "tar": "tar",
  "version": "1.12.0",
  "version-specberus": "3.2.5",
  "decision": "https://lists.w3.org/Archives/Public/www-style/2017May/0024.html",
  "results": {
    "status": "success",
    "jobs": {
      "retrieve-resources": {
        "status": "ok",
        "errors": []
      },
      "metadata": {
        "status": "ok",
        "errors": []
      },
⋮
```

**Comment by tabatkins** [comment]
Yeah, I'll have to check my console logs at work when I go in tomorrow.  *Something* in the pipeline sometimes outputs unformatted JSON, or does it with the wrong content-type so the whitespace collapses, or something.
