### ISSUE TITLE
public-tr-notifications loses error message if URL contains '&'

### ISSUE THREAD

**Issue by jyasskin** [w3c/echidna#487]
https://lists.w3.org/Archives/Public/public-tr-notifications/2017Sep/0091.html was created from the URL 'https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/w3c/permissions/master/index.bs&md-status=WD'. As you can see, there are no details in the email. I believe from the last time I debugged this that the problem is that the URL contains a '&', but I haven't re-checked that this time.

**Comment by tripu** [comment]
@jyasskin, many thanks for reporting.

It's a known issue; cf #474. I'm planning to take up work on that soon again.
