### ISSUE TITLE
Document the Echidna API

### ISSUE THREAD

**Issue by tripu** [w3c/echidna#54]
The 3 HTTP actions that Echidna understands (`version`, `status`, `request`) and their parameters, expected results and formats should be well documented, with examples.

**Comment by astorije** [comment]
For v1, only the `POST` to publish should be part of the API, as the other ones are not ready. I suggest removing the other ones from the code (but that'd be unfortunate), or to firewall them until we finalize.

**Comment by tripu** [comment]
`version` and `status` are the simplest, and easiest to document, @astorije. I think it would be worth spending a few hours to polish them a bit for `v1`. Three methods make an API, and having an API (even this limited) might spark more interest and encourage experimentation by early adopters&hellip; Besides, those two methods are useful for the development team and anyone helping, too.

**Comment by astorije** [comment]
Do we really need `version` at this stage?

Regarding `status`, I am okay to leave it for v1 but we can firewall it. It was never meant to be done for v1 since the only feedback is supposed to be email based right now. I am obviously in favor to improve that in the near future though, after v1 is released.

**Comment by tripu** [comment]
Agreed today that it'll be documented [here on the GH wiki](https://github.com/w3c/echidna/wiki) (at least for now).

**Comment by tripu** [comment]
[Done](https://github.com/w3c/echidna/wiki) by @astorije, @deniak & I. At least, it's good enough for launching.

**Comment by astorije** [comment]
Good job @tripu! Sorry I haven't been very productive on the wiki... I'll try to give it more care in the future.
