### ISSUE TITLE
Restrict “status” method to give info about particular publication jobs (instead of dumping all) and have the “request” method to return the ID of the new job

### ISSUE THREAD

**Issue by tripu** [w3c/echidna#55]
For privacy/security reasons, the HTTP GET method `status` of the API should *not* return all details about all publication jobs since the system was last started. Instead, it should accept an array of job IDs, and return info only about those jobs.

&hellip;which also means that the POST method `request` should always return the ID of the new publication job the user just submitted, instead of returning always a meaningless `200`&hellip;

**Comment by astorije** [comment]
@tripu, the POST should return a `201 Created` with a `Location` URI pointing at the resource it created... and we don't have the status page yet.
I suggest a `201 Created` with no `Location`, and keeping the other API endpoints closed from outside the team at this stage. We'll improve that later.

**Comment by tripu** [comment]
@astorije:
* OK to return `201`.
* I suggest we return the ID of the job in the response. We can prepend `echidna:` to that ID, if you want to make it a full-fledged URI; it doesn't have to be a web URL (not until the web UI is ready).

**Comment by astorije** [comment]
@tripu, I'll look into this tomorrow.
