### ISSUE TITLE
npm start doesn't take args

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/echidna#57]
README.md says one can run `npm start [STAGING_PATH]`, but npm doesn't seem to make it possible to pass arguments to the command.

(actually [npm2 might](https://github.com/npm/npm/pull/5518), but I don't think we should assume npm2 unless we must)

**Comment by astorije** [comment]
@dontcallmedom, indeed, I noticed that and forgot to add it to the README.

But actually, the [official doc itself](https://docs.npmjs.com/getting-started/installing-node) says that npm should be higher than 2.1.8 (mine is 2.3.0). I am not planning to ensure compatibility with npm 1.x.x.

Any specific reason why we should keep npm 1.x.x compatible? On the other hand, we can limit configuration to the config file if we have to and remove support for positional arguments :-/

**Comment by dontcallmedom** [comment]
I guess npm in ubuntu comes packaged as 1.4, but that's probably a weak argument :)

I've updated my install to use npm 2.x; I can now confirm that `npm start [ -- STAGING_PATH]` would work.

**Comment by astorije** [comment]
@dontcallmedom, for what it's worth, I only upgraded to npm 2.x a few days ago, when playing with the third party resources checker.

I'm pretty sure echidna this positional arguments issue is the only one limiting users to npm 2.x, so echidna is *almost* compatible with the stock npm from Ubuntu :)
