### ISSUE TITLE
dry run doesn't report error with change of deliverers

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/echidna#581]
I attempted to publish a document, first using the dry-run option to make sure all would be well. This reported success: https://labs.w3.org/echidna/api/status?id=d5929588-b9b8-4a2e-8fa4-8eb1da7388d6

But when I attempted to publish for reals, it reported fail: https://labs.w3.org/echidna/api/status?id=31e8f252-a9f6-4c54-b8bf-71db3872c05b

The failure says "Error: Documents changing their deliverers are not supported yet."

The dry-run option should have reported this error so I would have known I couldn't publish via Echidna.

**Comment by deniak** [comment]
Indeed, there are additional checks in the backend that Echidna cannot test easily but now that we have access to the W3C API, it should be easier to move these checks in Echidna.

**Comment by tripu** [comment]
We see this check as being part of pubrules (Specberus); we'll fix it there.
