### ISSUE TITLE
relaxing pubrules' checker: rel values

### ISSUE THREAD

**Issue by iherman** [w3c/echidna#596]
The pubrules checker, as echidna uses it, generates an error when there is a `<link>` element in the header with a not registered `rel` value. The problem is that we may have documents that do define a new `rel` value (ie, it is not _yet_ registered by IANA), and may want to use it for the generated document itself, too (under the adage "eat your own dog-food") but that is not possible because echidna rejects the publication.

Proposal: issue a warning, but let it through (for a Working Draft)

(Specific use case: the Web Publishing WG defines a [Web Publication Manifest](https://www.w3.org/TR/wpub/) which would be very much relevant for a TR document, too. There is a script to automatically add such a manifest to the document via respec, but it runs in the aforementioned problem.)

**Comment by deniak** [comment]
@iherman could you point me to a document that produces the error?
I believe the error is detected by validator.nu while checking the markup. While issuing a warning for each error returned by the validator isn't acceptable, we can certainly add an exception in pubrules for a specific error/specification. Of course, that requires approval from @plehegar first.

**Comment by iherman** [comment]
@deniak 

I have generated a (phony, because not to be published) WD in a separate branch:

https://rawgit.com/w3c/wpub/manifest-generation-script/snapshot/index.html

The file was generated by respec, using the additional script that does the manifest generation. Look for `<link rel="publication" href="#wp_manifest">` and the `<script>` element that follows.

Cc @plehegar

**Comment by deniak** [comment]
I confirm the error is [reported by validator.nu](https://validator.w3.org/nu/?doc=https://rawgit.com/w3c/wpub/manifest-generation-script/snapshot/index.html). Looking at the [spec](https://html.spec.whatwg.org/multipage/semantics.html#attr-link-rel), that's the expected behavior.

**Comment by iherman** [comment]
@deniak 

> I confirm the error is reported by validator.nu. Looking at the spec, that's the expected behavior.

I know/knew this. The question was whether it is possible for echidna to ignore that particular validator error for a Working Draft.

Cc: @plehegar

**Comment by deniak** [comment]
Yes, it is possible to add an exception for WD, CR and Notes, but @plehegar first needs to approve it.

**Comment by iherman** [comment]
@plehegar, can you give your approval or disapproval on this (just to close the issue in some way or other)? We plan to publish a new draft in the coming weeks, it would be good to know...

**Comment by plehegar** [comment]
I concur with @deniak . If the spec does define the rel value, we should enter it as an exception for that spec rather than downgrading the error. So, when it's time to publish your document, just remind Denis that the error is expected and he should add an exception in pubrules. fyi, exceptions are listed in
 https://github.com/w3c/specberus/blob/master/lib/exceptions.json

**Comment by iherman** [comment]
Thanks @plehegar; I will warn @deniak when the time comes:-)

**Comment by deniak** [comment]
@iherman ok to close that issue?

**Comment by iherman** [comment]
Will you add this relaxation rule only when I ping you or do it now? Will it be a permanent change or a one-off?

(But yes, I presume the issue itself can be closed.)

**Comment by deniak** [comment]
@iherman the exception has been added to pubrules and will be deployed soon

**Comment by iherman** [comment]
Merci!
