### ISSUE TITLE
Add a property file to replace hardcoded values

### ISSUE THREAD

**Issue by deniak** [w3c/echidna#6]

**Comment by astorije** [comment]
Some [follow-up] coming from @darobin.

**Comment by tripu** [comment]
Done. We already have [`config.js.example`](https://github.com/w3c/echidna/commits/master/config.js.example), which users should duplicate as `config.js`, and then edit.

--

Related: maybe getting rid of CLI arguments altogether (@astorije) or improving them, eg using [`nopt`](https://www.npmjs.com/package/nopt) (@darobin).

**Comment by astorije** [comment]
> Related: maybe getting rid of CLI arguments altogether (@astorije) or improving them, eg using [`nopt`](https://www.npmjs.com/package/nopt) (@darobin).

Yep, that's why I didn't close the issue right away :-)

**Comment by tripu** [comment]
I think it's best to open separate issues in cases like this, @astorije. Otherwise we have to change the title and description of existing issues, and we agreed that is a bad idea. No?

**Comment by astorije** [comment]
Done @tripu: #157
