### ISSUE TITLE
Fix certain fields in new mail messages

### ISSUE THREAD

**Issue by tripu** [w3c/echidna#605]
* [x] (Success) Fix URL of published spec (it points to the Echidna manifest now)
* [x] (Success) Fix *shortname* (it says `undefined` now)
* [ ] (Failure) Improve template to report issues?
Instead of composing that very long URL, can we use [GH issue templates](https://help.github.com/articles/creating-issue-templates-for-your-repository/)?
* [x] (Both) Add white space after `--` in signature
* [x] (Both) Simplify datetime (it's long, and difficult to parse at a glance)
eg `Tue Oct 02 2018 03:02:53 GMT+0000 (UTC)` &rarr; `Tue 2 Oct 2018 3:02 UTC`

---

* [Example of a success message](https://lists.w3.org/Archives/Public/public-tr-notifications/2018Oct/0004.html)
* [Example of a failure message](https://lists.w3.org/Archives/Public/public-tr-notifications/2018Oct/0003.html)

**Comment by tripu** [comment]
Thank you for updating the status of items in the list, @deniak!
I'll check that these 4 issues are indeed fixed once we deploy this in production and a few :+1: and :-1: messages have been sent.

**Comment by tripu** [comment]
Comparing
https://lists.w3.org/Archives/Public/public-tr-notifications/2018Oct/0056.html and
https://lists.w3.org/Archives/Public/public-tr-notifications/2018Oct/0062.html (`v1.13.4`)
with
https://lists.w3.org/Archives/Public/public-tr-notifications/2018Oct/0064.html (`v1.14.2`)
,
item no. 1 (URL of published spec) is fixed.

About item no. 2 (shortname): @deniak, see the last message; I wanted that to be the real *shortname*, ie `gamepad` (not `WD-gamepad-20181016`). To me, that's a short, handy reference to identify specs in conversation, and I see value in having it there. WDYT? Shall I try to fix that? Not worth it?

**Comment by deniak** [comment]
Indeed, I would prefer to see the shortname instead, but to me, the point of this email is to see whether a publication has succeeded or not, and if it failed, what are the errors so the final URL should be enough. That being said, we should probably get in touch with the editors to see what they are expecting.
