### ISSUE TITLE
Bug: getting CSS non-conforming...

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/echidna#613]
Found while trying to publish `http://w3c.github.io/manifest/ECHIDNA` (see the [publication job](https://labs.w3.org/echidna/api/status?id=0a8d8cb5-c58a-44a4-9fcc-06a830e63083))

And another attempt before that, we hit a CSS validation error... what we are unsure of is if it's complaining about the HTML file or the SVG files? I ask because we successfully published the specification via Echidna just before:

 https://labs.w3.org/echidna/api/status?id=b58ee36a-99d2-4886-8b56-fc1fdd99044a

But then we tried to publish some SVG images, and it started failing.

**Comment by deniak** [comment]
The CSS validator is currently giving inconsistent results. We are investigating but I don't think the error is coming from the spec.

**Comment by deniak** [comment]
@marcoscaceres This should be fixed now.

**Comment by marcoscaceres** [comment]
Awesome, thank you.
