### ISSUE TITLE
Respec documents served by raw.githubusercontent.com fail

### ISSUE THREAD

**Issue by deniak** [w3c/echidna#621]
raw.githubusercontent.com only serve documents in `text/plain`. This is an issue when the document needs to go through spec-generator as respec needs to execute some JS to work properly.
Since Echidna already runs its own local web server, it should be able to download these documents and serve them with the right content-type.

/cc @marcoscaceres

**Comment by jennyliang220** [comment]
It's fixed in spec-generator https://github.com/w3c/spec-generator/pull/523
