### ISSUE TITLE
Crash when server is not reachable

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/echidna#64]
If the URL of the target document is not reachable, echidna crashes instead of indicating failure to retrieve.

**Comment by astorije** [comment]
Well, not my fault if your server is unreachable!

Ok, ok, I'll provide a fix... :)

**Comment by astorije** [comment]
@dontcallmedom, you mean when the domain doesn't even exist? When we get a 404 (or another HTTP code), Echidna behaves properly, i.e. rejects the download and stops the publication process.

However, when trying to access a non-existing domain (like http://non.rien.de/rien) then indeed echidna crashes. Is that the scenario you meant? If so, I'll fix that tomorrow, thanks!

**Comment by astorije** [comment]
Argh, tests for my previous commits failed: the web server behind http://localhost/ on my laptop correctly serves a 404 but not on Travis CI... I guess that coincides with your issue, @dontcallmedom.

**Comment by dontcallmedom** [comment]
I confirm that by "not reachable", I meant any error at the networking level (IP, TCP, DNS) rather than HTTP errors.

**Comment by plehegar** [comment]
After fixing the statusCode error, I now get the following:
{
  "http://non.rien.oui/": {
    "url": "http://non.rien.oui/",
    "decision": "http://foo.com/",
    "isManifest": false,
    "token": "23234",
    "jobs": {
      "retrieve-resources": {
        "status": "error",
        "errors": [
          "Error: getaddrinfo ENOTFOUND"
        ]
      },
[....]

**Comment by plehegar** [comment]
btw, it took 5 seconds for the result to come back.

**Comment by plehegar** [comment]
btw, http://non.rien.de/rien takes a lot longer because that server is taking a while to answer

**Comment by plehegar** [comment]
e.g.
{
  "http://non.rien.de/rien": {
    "url": "http://non.rien.de/rien",
    "decision": "http://foo.com/",
    "isManifest": false,
    "token": "23234",
    "jobs": {
      "retrieve-resources": {
        "status": "error",
        "errors": [
          "Error: connect ETIMEDOUT"
        ]
      },
