### ISSUE TITLE
Bug: Continuing to autopublish after group switch

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/echidna#670]
Getting "Documents changing their deliverers are not supported yet." error... Could use some guidance on how I move existing specs over to auto-publish in the new WebAppsWG.   

Found while trying to publish `http://w3c.github.io/manifest/ECHIDNA` (see the [publication job](https://labs.w3.org/echidna/api/status?id=4e8bddd5-14ce-402e-90da-f7e7eb7adf2f)

cc @siusin, @deniak

**Comment by deniak** [comment]
Sorry, I completely missed that issue. I'm guessing this is no longer an issue but indeed, Echidna doesn't support the deliverer switch yet as it affects how we deal with IPP and the call for exclusions.
We did simplify a few things with the release of process 2020 though so we may be able to remove that limitation in the near future.
