### ISSUE TITLE
Publication token creation requires special privileges

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/echidna#672]
The auto-publish token request page requires special privileges:
https://www.w3.org/Web/publications/register

Would be nice if Chairs had access to this.

**Comment by deniak** [comment]
I think that's reasonable. @plehegar WDYT?

**Comment by deniak** [comment]
ping @plehegar

**Comment by plehegar** [comment]
hu... missed that one. sorry :(

+1 to open to Chairs of course.

**Comment by deniak** [comment]
I opened the form to the chairs as well!

**Comment by plehegar** [comment]
Denis, want me to announce this to team contacts and chairs or would you like to do it?

**Comment by deniak** [comment]
Sent: https://lists.w3.org/Archives/Member/chairs/2019OctDec/0077.html

**Comment by marcoscaceres** [comment]
Thanks for opening this up to Chairs! :)
