### ISSUE TITLE
Bug: Manifest spec times out

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/echidna#675]
Found while trying to publish `http://w3c.github.io/manifest/ECHIDNA` (see the [publication job](https://labs.w3.org/echidna/api/status?id=ba8656c9-8f5c-4d7d-96d6-540b359d80f2)).

The manifest spec keeps timing out... however, [loading the spec through the spec generator](https://labs.w3.org/spec-generator/?type=respec&url=http%3A%2F%2Fw3c.github.io%2Fmanifest%2Findex.html%3FspecStatus%3DWD%26shortName%3Dappmanifest) works ok. For whatever reason, it is slow to generate.... maybe we should boost the timeout? Sometimes it responds quite quickly. 

Generating it locally is fairly fast... definitely not 30 seconds.

**Comment by deniak** [comment]
I see it [finally went through](https://github.com/w3c/echidna/issues/675).
Timeout is already set to [30sec](https://github.com/w3c/spec-generator/blob/master/generators/respec.js#L11). If it's timing out, it probably means there's an issue with spec-generator. Loading the URL seems pretty fast so I'm closing that issue for now and if it occurs again in the future, I'll investigate more.

**Comment by marcoscaceres** [comment]
Thanks for checking it @deniak.
