### ISSUE TITLE
Some URLs in wiki are not reachable

### ISSUE THREAD

**Issue by jennyliang220** [w3c/echidna#735]
## suggested request tool not reachable
doc: https://github.com/w3c/echidna/wiki/How-to-use-Echidna#using-echidna-publication-without-curl
suggest tool: https://www.hurl.it/
could be replaced by https://www.apirequest.io/
![image](https://user-images.githubusercontent.com/8498677/85941179-df6b5980-b953-11ea-9286-c61d8c0fc823.png)

## get user is site not reachable
doc: https://github.com/w3c/echidna/wiki/Preparing-your-document#data-editor-id
suggest link: https://www.w3.org/2000/09/dbwg/person
![image](https://user-images.githubusercontent.com/8498677/85941166-c2368b00-b953-11ea-87c4-2be9dbbeb5ea.png)

**Comment by deniak** [comment]
Good catch @jennyliang220. Both pages are now updated.
