### ISSUE TITLE
Bug: tries to interpret date where there isn't a date

### ISSUE THREAD

**Issue by rhiaro** [w3c/echidna#773]
ECHIDNA is failing because a date in the SotD cannot be parsed. The only problem is - it's not a date. It's a portion of a contract number related to how some of the work was funded. It looks sort of like a date because it has numbers and hyphens in. Specberus is interpreting the string "16-1-00" as a date from the longer string "HSHQDC-16-R00012-H-SB2016-1-002".

The weirdest part is that this error occurs in did-spec-registries but the same string occurs in the same place in did-core and the error does not occur there. The difference is that did-spec-registries is a NOTE and did-core is a WD on the REC track.

Found while trying to publish `https://w3c.github.io/did-spec-registries/ECHIDNA` (see the [publication job](https://labs.w3.org/echidna/api/status?id=e1c204c7-d1cf-450d-a947-0f3d340c5abb)).

cc @iherman

**Comment by deniak** [comment]
This should now be fixed. The regex for the dates detection was not handling these cases properly.
