### ISSUE TITLE
The testbed web interface / console is pretty silent

### ISSUE THREAD

**Issue by astorije** [w3c/echidna#82]
I am currently working on #48 and learning how to use the test bed the hard way.

Since I am heavily butchering `app.js`, I would like to see what happens when I try to publish a document. I actually discovered the test bed due to this, after grumbling that I cannot use the web UI. It seems like a neat feature but right now it seems to be pretty silent.

Where can I see the `history` / the content of the `jobs`? Since I am breaking stuff, I am trying to see what happens and right now I just get `undefined` for most of the things I click. Could you try the test bed on a clean clone to see what I mean? Maybe I am getting confused somewhere but at the moment I really a tour...

(PS: As you might guess, don't try to refactor or clean up `app.js` :-) )

**Comment by astorije** [comment]
@tripu, do you have plans to work on this soon? I think it is an urgent matter as it is pretty difficult to develop on Echidna since the previous UI was removed. It was way easier when the resulting JSON was just spit at us, now it's a nightmare to get any feedback :-(

**Comment by tripu** [comment]
My old idea of a testbed to automate tests on a web interface was abandoned: the test suite has grown lately and is quite comprehensive now, even using the W3C API to check stuff.

Closest to this now is #297.
