### ISSUE TITLE
Allow to annotate TAR publication request to identify source

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/echidna#831]
When an automated Echidna publication request via tar upload fails before metadata can be parsed, it's pretty hard to identify what spec generated the problem, e.g. nothing helps understanding that https://lists.w3.org/Archives/Public/public-tr-notifications/2021Apr/0003.html is linked to a failure in the image-capture spec.

It would be useful if echidna supported a parameter that could be used to annotate the request to help id it when it goes wrong; I could then get the spec-prod action to automatically set it (e.g. to the spec shortname or the spec repo).

**Comment by deniak** [comment]
You can now use the parameter `annotation` (see https://github.com/w3c/echidna/wiki/How-to-use-Echidna#optional-parameters) that will be displayed in the report.
