### ISSUE TITLE
Bug: Payment handler .tar failing

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/echidna#844]
Found while trying to publish `echidna.tar` (see the [publication job](https://labs.w3.org/echidna/api/status?id=ffc35e8b-9a29-402e-baaa-6ea6a1dea8b4)

Any chance we could get more details about what's failing in the .tar file? Or maybe there is a way of accessing the .tar file so I can take a look at why the document can't be parsed? 

It was generated via spec-prod. 

cc @ianbjacobs.

**Comment by deniak** [comment]
The document submitted is actually an ED.
I've submitted a PR to try to fix the issue: https://github.com/w3c/payment-handler/pull/388

**Comment by marcoscaceres** [comment]
Awesome, thank you. Sent a PR to update the spec-prod docs too:
https://github.com/w3c/spec-prod/pull/56
