### ISSUE TITLE
User search form is inaccessible

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/echidna#85]
When I go to https://www.w3.org/users/search

It returns me a 403! This means I can't search for my co-editors' to add to my spec :(

**Comment by astorije** [comment]
Hi @marcoscaceres!

This is a team-restricted link at it currently gives full access to our user accounts.

For the time being, we will ask that you guys individually get your ID from the ["my profile" page](https://www.w3.org/users/myprofile) (it gets redirected and then shows your ID in the URL). We will work to change/improve that so feedback is appreciated until this happens.

**Comment by marcoscaceres** [comment]
I'll ask the other editors to get their numbers.
