### ISSUE TITLE
Bug: Failed to autopublish web manifest spec

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/echidna#873]
Tried to publish the Web Manifest (ReSpec) spec using spec-prod, but Echidna doesn't seem to detect it as a publishable document for some reason (but I can't figure out what that is). 

Found while trying to publish “echidna.tar” (see the [publication job](https://labs.w3.org/echidna/api/status?id=0029a52b-a758-44e8-a2d3-d3edadf26ec5)).

**Comment by deniak** [comment]
The document submitted by spec-prod is actually the editor's draft.
It seems the [workflow](https://github.com/w3c/manifest/blob/gh-pages/.github/workflows/action.yml) is missing some config options:
```
W3C_BUILD_OVERRIDE: |
            specStatus: WD
            shortName: appmanifest
```

**Comment by marcoscaceres** [comment]
ah, thanks! fixed
