### ISSUE TITLE
Automated testing?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/echidna#91]
In the readme, there is a Automated testing section - but that seems unhelpful to those looking at the project (i.e., why would a user want to run the tests?). Maybe move that stuff to the wiki.

**Comment by tripu** [comment]
I understand it may be confusing to some, @marcoscaceres. But isn't this the usual distinction between *users* and *developers* of a piece of software?

If you're looking at the source code of Node.js on GH, [you'll see instructions to run their automated tests](https://github.com/joyent/node#to-run-the-tests). [Same for AngularJS](https://github.com/angular/angular.js#running-tests). Users of the tool know that's not meant for them; it's there to contributors of the project.

**Comment by astorije** [comment]
I agree with @tripu here: the README should contains instructions about the project itself, how to build it, test it, run it, ...

Then the wikis are user-oriented (and maybe the README file should start with a line saying "To learn how to make use of Echidna at W3C, please refer to the wiki"] with a link to it.

That being said, I think it would be useful to have the wiki split in 2, one part user-oriented, and one part dev-oriented. The README would still keep the details explained above, while kept minimalist.

Would you be okay with that, guys?

**Comment by marcoscaceres** [comment]
The problem is that the README is (was?) mixing user testing and the project's tests. In particular, the section "Web-based testbed" seems to be for users of Echidna (instead of Echidna devs), or did I read that wrong?

**Comment by astorije** [comment]
Hi @marcoscaceres, actually the "web-based testbed" is also intended for devs as it essentially provides a bunch of fake documents that will consistently¹ pass and fail the whole system. None of the tests described in the README are intended for users. Please make suggestions in #96 to make that clearer, it's not easy when you see things *from the inside* :-)

¹ Meaning, for example, that some fake documents are generated with today's date to make sure they pass the checkers whenever you run the test suite.

**Comment by marcoscaceres** [comment]
Ok, thanks for the clarification. All making much more sense now :) Thanks for listening to the feedback.
