### ISSUE TITLE
Bug: “latest-is-not-previous” on payment request

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/echidna#915]
Found while trying to publish “echidna.tar” (see the [publication job](https://labs.w3.org/echidna/api/status?id=a20abc3e-164b-42da-93e8-9e8334f1fdef)).

Hi @deniak, sorry to bother you with this, but I'm a bit confused as to what I'm doing wrong with the above? The previous publish date is set to 2021-06-29, but it's failing. Can you help me understand why?  

Here is the link to the publication history showing the last published date: 
https://www.w3.org/standards/history/payment-request

**Comment by marcoscaceres** [comment]
(I did try 2019-12-12 also, but it didn't like it either)

**Comment by marcoscaceres** [comment]
In case it helps, latest attempt is  https://labs.w3.org/echidna/api/status?id=ee7f466e-13c7-49fc-9760-e7cbd4e32c1b

**Comment by deniak** [comment]
The snapshot sent to Echidna (attached) specify the following previous version:
https://www.w3.org/TR/2019/CR-payment-request-20191212/

The previous version should actually be: https://www.w3.org/TR/2021/CRD-payment-request-20210629/

I'll try to see why spec-prod is not picking the right version.

[Payment Request API.zip](https://github.com/w3c/echidna/files/6861579/Payment.Request.API.zip)

**Comment by deniak** [comment]
I wonder if it's not related to the [`previousMaturity`](https://github.com/w3c/payment-request/blob/gh-pages/index.html#L65). I'm guessing it should be `CRD` instead of `CR`

**Comment by marcoscaceres** [comment]
"CRD" worked! Thanks @deniak! I owe you one!!! 🏆
