### ISSUE TITLE
Make Echidna run locally without failing

### ISSUE THREAD

**Issue by astorije** [w3c/echidna#97]
Although Echidna is supposed to be run locally, there are parts of the system that currently fail if you do not have a full W3C setup. This issue is meant to keep track of what needs to be done and what it already done to fix that.

Here are a list of the steps with their status regarding ability to run locally:
- [x] **Document Downloader**: does not interact with W3C systems
- [ ] **Specberus**: works as a standalone project and as a Node module, but still markup/css validator issue
- [x] **Token Checker**: a mock API is provided
- [x] **Third Party Checker**: works as a standalone project and as a Node module
- [x] **W3C DB Publisher**: a mock API is provided
- [x] **TR Installer**: shares interface with `cp -r` so it can be mocked locally
- [x] **Shortlink Updater**: shamefully use `#` as a local command... we can probably do better, but at least it works...
- [ ] Serve the staging documents through a webserver started with Node.js rather than expect the configuration to point to a server set up somewhere else

**Comment by astorije** [comment]
I should actually use the [issue template](https://github.com/w3c/echidna/blob/master/CONTRIBUTING.md#report-a-bug-or-suggest-a-feature-idea) for this.
@anssiko or someone else, care to run it locally to share the current output? Thanks!

**Comment by astorije** [comment]
@anssiko, I am currently working on this one, it should be ready soon.

**Comment by anssiko** [comment]
@astorije awesome, let me know when I can give it a spin.

**Comment by astorije** [comment]
@anssiko actually, you already can, but there are still things that need to be fixed. Here is what you have to do:

- Somewhere on your machine, `git clone https://github.com/w3c/echidna.git && cd echidna && git checkout astorije/make-it-standalone`
- `npm install` to install the dependencies
- `cp config.js.example config.js` to create the configuration file and then edit `global.DEFAULT_TEMP_LOCATION` and `global.DEFAULT_RESULT_LOCATION` to directories the webserver can write (I use `/home/jeremie/public_html/tr`), and `global.DEFAULT_HTTP_LOCATION` to a web-served location (I use `http://localhost/~jeremie/tr`)
- I actually broke Echidna in a previous commit, sorry, so until #169 is merged, you need to manually apply the fix with `git merge astorije/fix-orchestrator`
- The last (OK, let's say "one of the last") thing that will still not work locally can be manually fixed with the following: [open `lib/specberus-wrapper.js` and, line 43](https://github.com/w3c/echidna/blob/739ded484538600f8d94e7f34173ad72b82889c9/lib/specberus-wrapper.js#L43), replace `simple-validation` with `no-validation`. I am thinking of solutions to fix this but I can't find an ideal (FP-style :P) way to do so.

After that, Echidna should run locally. Let me know if you get any other issue!

**Comment by astorije** [comment]
@anssiko see #171 for implementation details.

**Comment by tripu** [comment]
@astorije, now that [Specberus is an npm package](https://www.npmjs.com/package/specberus), does that mean we can tick the last box in this checklist?

**Comment by astorije** [comment]
@tripu, unfortunately no, I still have an issue with this, which corresponds to the last bullet of [my previous comment](https://github.com/w3c/echidna/issues/97#issuecomment-100364638). I should have something soon, I'll let you know.

**Comment by tripu** [comment]
Echidna runs stand-alone well now.
